language: java
jdk:
- openjdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: wtJBqx1oWU9SCkCwha7qoesRakRLuJHKy+7vKrgFFPZs8sWs2AxOMigWAW1BjXwal06HbUHd0OGO1n9URB1vndyW9iTNGvCIKt0xowbU7TbDoLLheIh4Ichug8vzrOtD5VGesaFmUgF27uWfzb3QM4XRHVbsqjFlG09zoLdkMd4RbVRhVbxFxmFRgQOHPKY70bpL1zaccpzQsyD2O5QytoMrE/32rerJp9r98DphR/TfZIrN1W9FpJzClBqjh9OeYPPOMiV40GfBnEa+7IbluypdtGOoA2MYdCBmmySuY7hl1+eprU0TMRwA0On2udeIIR0V+DkymcLW/+CLyFJjlxYZ2cQa1dCexdYhgaiJAAWsj0tF9Wj/gIb+gTaYCQrsrI7l1JwgVbpeUFRtM//OBSPCkvT88HMoGsQ9hyMG9fZaQFib6TZpzF5trW+3ddbU6FnruEOPVSUZf6iEPukw0lJq3UOK8LMzJmnBUNOkK7DdMr2ycPrKGLPk3yepzxHwInjJmBVhnMwFxmBAJTBngQ/KNFtwYxe4ftK7lUkvHWdxdqoprPHl2MLG3KrpcrkJ3bsA/M6DbqYuObfr4oGKevx2gHWtCo+beLJXMfnkXvmmAZJNhK5NH+SexzHG+bf6+fqhowDDj9o7qm/FqbGVkYzp0ipRCD6sxI/FHj/WZmA=
  file: build/libs/*
  on:
    repo: ltamaster/execution-mode-later-plugin
    tags: true
  file_glob: true
  skip_cleanup: true

